import { spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { dataDir } from "./data-dir";
import { daemonLaunchVector } from "./launch-vector";
import type { ShortcutResult } from "../../shared/dto";

export type { ShortcutFailure, ShortcutResult } from "../../shared/dto";

// ---------------------------------------------------------------------------
// Desktop shortcuts for ONE managed process (or a whole project).
//
// The .lnk is a thin trigger into the daemon, never a second supervisor: it runs
// `<this build> open-process <.devwebui path> <localId>` (see cli.ts), which boots
// the daemon if it's cold, loads the project if it isn't registered, and POSTs the
// normal start action — so links/companions/waitForPort/logs/stop all come from the
// one code path the GUI already uses.
//
// Identity is carried as (.devwebui absolute path + localId), NOT the global process
// id. The id is derivable from the path anyway (`projectIdFromPath` is a hash of it,
// projects/file-store.ts), so the path is strictly more information: it additionally
// lets the launcher re-load a project the user has since removed from DevWebUI. The
// shortcut therefore survives daemon restarts, auto-updates, and remove/re-add; only
// physically moving the repo breaks it, which no id scheme could survive either.
// ---------------------------------------------------------------------------

const HERE = path.dirname(fileURLToPath(import.meta.url));

/**
 * The hidden launcher. Double-clicking a .lnk whose target is a console program
 * (bun.exe, or the console-subsystem compiled devwebui.exe) flashes a console
 * window for as long as the launch takes; routing through wscript.exe + this
 * script means no flash at all. Same trick, and same reason, as the tray's
 * misc/Tray-Launch.vbs — but written into the DATA dir rather than read from
 * misc/, because misc/ ships with the repo and not with dist/devwebui.exe.
 *
 * wscript has already parsed the command line, so each WScript.Arguments entry is
 * one clean argument; we re-quote the ones containing spaces and hand the joined
 * line to Run with windowStyle 0 (hidden) and bWaitOnReturn False (don't block).
 */
const LAUNCHER_VBS = `' DevWebUI — hidden launcher for desktop shortcuts. Generated by the daemon
' (server/src/shortcuts.ts); regenerated on every shortcut creation, do not edit.
Option Explicit
Dim sh, cmd, i, a
Set sh = CreateObject("WScript.Shell")
cmd = ""
For i = 0 To WScript.Arguments.Count - 1
  a = WScript.Arguments(i)
  If InStr(a, " ") > 0 Then a = """" & a & """"
  If cmd <> "" Then cmd = cmd & " "
  cmd = cmd & a
Next
If cmd <> "" Then sh.Run cmd, 0, False
`;

/** Write (refresh) the launcher script in the data dir and return its path. */
function ensureLauncherVbs(): string {
  const dir = dataDir();
  mkdirSync(dir, { recursive: true });
  const file = path.join(dir, "launcher.vbs");
  // Rewritten every time rather than only-if-missing so an older build's launcher
  // can never linger with stale semantics.
  writeFileSync(file, LAUNCHER_VBS, "utf8");
  return file;
}

/**
 * Icon for the .lnk. The brand .ico lives in misc/, which exists in a checkout but
 * is NOT copied next to the compiled binary (scripts/build.ts ships the exe + web
 * assets only), so fall back through: repo misc/ → beside the exe → the exe's own
 * embedded icon (always resolvable, never pretty-fails).
 */
function iconLocation(launcherExe: string): string {
  const candidates = [
    path.resolve(HERE, "..", "..", "misc", "DevWebUI.ico"),
    path.join(path.dirname(process.execPath), "DevWebUI.ico"),
  ];
  for (const c of candidates) if (existsSync(c)) return `${c},0`;
  return `${launcherExe},0`;
}

/**
 * A label safe to use as a .lnk filename: Windows forbids `< > : " / \ | ? *` and
 * control characters outright, and silently mangles a name with a trailing dot or
 * space. Hyphens are legal and deliberately preserved: the process label reads
 * "<project> - <process>", so folding them away would eat the separator.
 */
const FORBIDDEN_IN_FILENAME = /[<>:"/\\|?*]/g;

export function safeFileLabel(label: string): string {
  const printable = [...label].map((ch) => ((ch.codePointAt(0) ?? 0) < 32 ? " " : ch)).join("");
  return (
    printable
      .replace(FORBIDDEN_IN_FILENAME, " ")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 96)
      .replace(/[. ]+$/, "") || "DevWebUI"
  );
}

/** Quote one argument for the .lnk's Arguments string. */
function quote(value: string): string {
  return `"${value}"`;
}

/**
 * Build the .lnk via WScript.Shell (the same COM path misc/New-TrayShortcut.ps1 uses,
 * inheriting its hard-won gotchas — see the ANSI note below).
 *
 * Every caller-supplied value crosses into PowerShell as an ENVIRONMENT VARIABLE
 * rather than being interpolated into the -Command string. Process names and repo
 * paths are arbitrary user text; string-building a shell command out of them is how
 * you get quoting bugs at best and command injection at worst. Env vars are passed
 * as data by the OS and PowerShell never re-parses them.
 */
function runShortcutPs(env: Record<string, string>): Promise<ShortcutResult> {
  const ps = [
    "$ErrorActionPreference = 'Stop'",
    // Force stdout to UTF-8. PowerShell otherwise encodes it in the console's OEM
    // codepage, and Node decodes as UTF-8 — so the $final path echoed back at the end
    // would come home mojibake ("RēDesign" -> "R?Design") for any non-ASCII label,
    // and the GUI would report a path that doesn't exist.
    "[Console]::OutputEncoding = [System.Text.Encoding]::UTF8",
    // GetFolderPath resolves the REAL Desktop, honouring OneDrive/Known-Folder
    // redirection — a hardcoded ~\Desktop is wrong on most modern Windows setups.
    "$desktop = [Environment]::GetFolderPath('Desktop')",
    "if (-not $desktop) { throw 'could not resolve the Desktop folder' }",
    "$name = $env:DWU_NAME",
    "$final = Join-Path $desktop ($name + '.lnk')",
    // WScript.Shell saves the .lnk through an ANSI path, so it can only WRITE to an
    // ASCII filename; a non-ASCII name is silently transliterated (ē -> e). Save to an
    // ASCII temp then rename via the Unicode filesystem API, which preserves it.
    // (Lifted from misc/New-TrayShortcut.ps1:30-46 — same COM limitation, same cure.)
    //
    // The temp name is a caller-supplied UNIQUE token, not a slug of the label: two
    // concurrent creations whose labels reduce to the same ASCII string (trivially,
    // any two fully non-Latin names, which both reduce to nothing) would otherwise
    // pick the same temp path and race — one clobbering or deleting the other's file
    // mid-flight. Uniqueness makes concurrent creation safe by construction.
    "$isAscii = $true",
    "foreach ($ch in $name.ToCharArray()) { if ([int][char]$ch -gt 127) { $isAscii = $false; break } }",
    "if ($isAscii) { $tmp = $final } else { $tmp = Join-Path $desktop ($env:DWU_TMP + '.lnk') }",
    "if (Test-Path -LiteralPath $tmp) { Remove-Item -LiteralPath $tmp -Force }",
    // finally: never leave a half-built "DevWebUI-tmp-<uuid>.lnk" sitting on the user's
    // Desktop if Save() or the rename throws partway.
    "try {",
    "  $ws = New-Object -ComObject WScript.Shell",
    "  $sc = $ws.CreateShortcut($tmp)",
    "  $sc.TargetPath = Join-Path $env:SystemRoot 'System32\\wscript.exe'",
    "  $sc.Arguments = $env:DWU_ARGS",
    "  $sc.WorkingDirectory = $env:DWU_CWD",
    "  $sc.IconLocation = $env:DWU_ICON",
    // The Description property is ANSI-limited too and silently drops non-ASCII, so
    // callers pass a plain-ASCII tooltip rather than have it disagree with the name.
    "  $sc.Description = $env:DWU_DESC",
    "  $sc.Save()",
    "  if ($tmp -ne $final) { Move-Item -LiteralPath $tmp -Destination $final -Force }",
    "} finally {",
    "  if (($tmp -ne $final) -and (Test-Path -LiteralPath $tmp)) { Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue }",
    "}",
    "[Console]::Out.Write($final)",
  ].join("; ");

  return new Promise((resolve) => {
    let out = "";
    let err = "";
    let done = false;
    const finish = (r: ShortcutResult) => {
      if (done) return;
      done = true;
      clearTimeout(timer);
      resolve(r);
    };
    const timer = setTimeout(
      () => finish({ ok: false, reason: "powershell-failed", detail: "timed out" }),
      20_000,
    );
    try {
      const child = spawn("powershell", ["-NoProfile", "-NonInteractive", "-Command", ps], {
        windowsHide: true,
        env: { ...process.env, ...env },
      });
      child.stdout?.on("data", (d: Buffer) => {
        out += d.toString();
      });
      child.stderr?.on("data", (d: Buffer) => {
        if (err.length < 4096) err += d.toString();
      });
      child.on("close", (code) => {
        const file = out.trim();
        if (code === 0 && file) finish({ ok: true, path: file });
        else
          finish({
            ok: false,
            reason: "powershell-failed",
            detail: err.trim() || `exit ${code}`,
          });
      });
      child.on("error", (e) =>
        finish({ ok: false, reason: "powershell-failed", detail: e.message }),
      );
    } catch (e) {
      finish({ ok: false, reason: "powershell-failed", detail: (e as Error).message });
    }
  });
}

/** Shared assembly for both shortcut flavours; `verb` is the cli.ts command to run. */
async function create(opts: {
  verb: "open-process" | "open-project";
  devwebuiPath: string;
  /** Present for a process shortcut, absent for a project one. */
  localId?: string;
  /** The .lnk filename (without .lnk) AND what the user reads under the icon. */
  label: string;
  /** ASCII-only tooltip (see the Description note in runShortcutPs). */
  description: string;
}): Promise<ShortcutResult> {
  if (process.platform !== "win32") return { ok: false, reason: "unsupported-platform" };

  const args = [opts.devwebuiPath, opts.localId].filter((v): v is string => !!v);
  // A literal double quote would break out of the .lnk Arguments string; nothing
  // legitimate contains one (Windows forbids `"` in paths, and localId is
  // ^[A-Za-z0-9._-]+$ per shared/schema.ts), so refuse rather than try to escape.
  if (args.some((v) => v.includes('"'))) return { ok: false, reason: "bad-input" };

  const vbs = ensureLauncherVbs();
  const vector = daemonLaunchVector();
  const launcherExe = vector[0]!;
  // wscript.exe "<launcher.vbs>" "<bun|devwebui.exe>" ["<index.ts>"] "<verb>" "<path>" ["<localId>"]
  const lnkArgs = [vbs, ...vector, opts.verb, ...args].map(quote).join(" ");

  return runShortcutPs({
    DWU_NAME: safeFileLabel(opts.label),
    // Unique per invocation — see the temp-name note in runShortcutPs.
    DWU_TMP: `DevWebUI-tmp-${randomUUID()}`,
    DWU_ARGS: lnkArgs,
    // The repo folder is the friendliest cwd: "Open file location" from the .lnk's
    // properties lands the user in the project, not in Bun's install dir.
    DWU_CWD: path.dirname(opts.devwebuiPath),
    DWU_ICON: iconLocation(launcherExe),
    DWU_DESC: opts.description,
  });
}

/** Desktop shortcut that starts ONE process (plus its linked group + companions). */
export function createProcessShortcut(opts: {
  devwebuiPath: string;
  localId: string;
  processName: string;
  projectName: string;
}): Promise<ShortcutResult> {
  return create({
    verb: "open-process",
    devwebuiPath: opts.devwebuiPath,
    localId: opts.localId,
    label: `${opts.projectName} - ${opts.processName}`,
    description: "Start this dev server with DevWebUI",
  });
}

/** Desktop shortcut that starts EVERY process in a project. */
export function createProjectShortcut(opts: {
  devwebuiPath: string;
  projectName: string;
}): Promise<ShortcutResult> {
  return create({
    verb: "open-project",
    devwebuiPath: opts.devwebuiPath,
    label: opts.projectName,
    description: "Start this codebase's dev servers with DevWebUI",
  });
}
